# Generated by Django 5.0.1 on 2024-01-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
