# Generated by Django 5.0.1 on 2024-01-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productivity',
            name='end',
        ),
    ]
