# Generated by Django 5.0.1 on 2024-01-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0002_remove_productivity_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivity',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
