# Generated by Django 5.0.1 on 2024-01-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0002_alter_vehicle_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
