# Generated by Django 5.0.1 on 2024-01-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0003_productivity_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivity',
            name='day_production',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
