# Generated by Django 5.0.1 on 2024-01-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0003_alter_employee_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
