# Generated by Django 5.0.1 on 2024-02-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0004_alter_employee_is_staff'),
        ('vms_app', '0004_productivity_day_production'),
    ]

    operations = [
    ]
