# Generated by Django 5.0.1 on 2024-02-06 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0006_productivity_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='productivity',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_productivity_set', to='vms_app.vehicle'),
        ),
    ]
