# Generated by Django 5.0.1 on 2024-02-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0008_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
