# Generated by Django 5.0.1 on 2024-02-07 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0009_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivity',
            name='vehicle',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_working': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_productivity_set', to='vms_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
