# Generated by Django 5.0.1 on 2024-02-07 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0010_alter_productivity_vehicle_alter_vehicle_is_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_supervised_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productivity',
            name='routes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, to='vms_app.route'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_supervised_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
