# Generated by Django 5.0.1 on 2024-02-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0012_ward_workshop_zone_remove_route_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
