# Generated by Django 5.0.1 on 2024-02-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0014_alter_route_ward_alter_route_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productivity',
            old_name='rounds',
            new_name='fifth_trip_ton',
        ),
        migrations.AddField(
            model_name='productivity',
            name='first_trip_ton',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productivity',
            name='fourth_trip_ton',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productivity',
            name='in_km',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='productivity',
            name='out_km',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='productivity',
            name='second_trip_ton',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productivity',
            name='shift',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productivity',
            name='sixth_trip_ton',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productivity',
            name='third_trip_ton',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productivity',
            name='total_ton',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productivity',
            name='total_trip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
