# Generated by Django 5.0.1 on 2024-02-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0017_remove_productivity_total_ton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productivity',
            name='routes',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to='vms_app.route'),
        ),
    ]
