# Generated by Django 5.0.1 on 2024-02-24 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0018_alter_employee_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintanenceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='transferregister',
            name='accident_location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='transferregister',
            name='accident_severity',
            field=models.CharField(choices=[('Fatality', 'Fatality'), ('Near Miss', 'Near Miss'), ('Property Damage', 'Property Damage')], default='Fatality', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferregister',
            name='accident_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferregister',
            name='action_needed',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferregister',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferregister',
            name='cause_of_accident',
            field=models.CharField(choices=[('Mechanical Failure', 'Mechanical Failure'), ('Hydraulic Failure', 'Hydraulic Failure'), ('Over Speeding', 'Over Speeding'), ('Poor Visibility', 'Poor Visibility'), ('Lack of Attention', 'Lack of Attention'), ('Influence of Alcohol', 'Influence of Alcohol'), ('Lack of Training', 'Lack of Training'), ('Others', 'Others')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferregister',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transferregister',
            name='driver_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferregister',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transferregister',
            name='remark',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('Accident', 'Accident'), ('Breakdown', 'Breakdown'), ('General Maintanence', 'General Maintanence')], max_length=100)),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('incident_time', models.DateTimeField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=250, null=True)),
                ('incident_brief', models.TextField()),
                ('cause_of_incident', models.TextField()),
                ('investigated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('driver_comment', models.TextField()),
                ('zonalmanager_comment', models.TextField()),
                ('mechanic_comment', models.TextField()),
                ('estimatedrepair_cost', models.FloatField(blank=True, null=True)),
                ('cost_responsible', models.CharField(choices=[('Company', 'Company'), ('Insurance', 'Insurance'), ('Thirdparty', 'Thirdparty')], max_length=250)),
                ('action_needed', models.TextField()),
                ('remark', models.TextField()),
                ('sent_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshopsincidents_set', to='vms_app.workshop')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vms_app.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='AccidentLog',
        ),
    ]
