# Generated by Django 5.0.1 on 2024-02-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0023_rename_estimatedrepair_cost_incidentlog_estimated_repair_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferregister',
            old_name='transferred_date',
            new_name='transfer_date',
        ),
    ]
