# Generated by Django 5.0.1 on 2024-02-24 16:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0024_rename_transferred_date_transferregister_transfer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivity',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productivity',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productivity',
            name='end_image',
            field=models.ImageField(blank=True, null=True, upload_to='productivity_end/'),
        ),
        migrations.AddField(
            model_name='productivity',
            name='start_image',
            field=models.ImageField(default='', upload_to='productivity_start/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productivity',
            name='shift',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], default='I', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productivity',
            name='vehicle',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True, 'is_working': False}, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_productivity_set', to='vms_app.vehicle'),
            preserve_default=False,
        ),
    ]
