# Generated by Django 5.0.1 on 2024-02-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0026_alter_productivity_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivity',
            name='trip_ton',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
