# Generated by Django 5.0.1 on 2024-02-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0027_productivity_trip_ton'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productivity',
            unique_together={('shift', 'vehicle', 'created_date')},
        ),
    ]
