# Generated by Django 5.0.1 on 2024-02-25 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms_app", "0028_alter_productivity_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="km_estimation",
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="load_estimation",
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name="productivity",
            name="shift",
            field=models.CharField(
                choices=[
                    ("I", "I"),
                    ("II", "II"),
                    ("III", "III"),
                    ("Others", "Others"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="TripHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("Others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trip_count", models.IntegerField()),
                ("trip_load", models.IntegerField()),
                ("trip_efficiency", models.FloatField(default=0)),
                ("trip_start_time", models.DateTimeField(auto_now_add=True)),
                ("updted_on", models.DateTimeField(auto_now=True)),
                ("trip_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicle_trips_set",
                        to="vms_app.vehicle",
                    ),
                ),
            ],
        ),
    ]
