# Generated by Django 5.0.1 on 2024-02-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0029_route_km_estimation_vehicle_load_estimation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='time_estimation',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
