# Generated by Django 5.0.1 on 2024-02-26 00:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0030_route_time_estimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('out_km', models.FloatField(blank=True, default=0.0, null=True)),
                ('start_image', models.ImageField(upload_to='shift_start/')),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('in_km', models.FloatField(blank=True, default=0.0, null=True)),
                ('end_image', models.ImageField(blank=True, null=True, upload_to='shift_end/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('shift_name', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('Others', 'Others')], max_length=100)),
                ('estimation', models.IntegerField(blank=True, null=True)),
                ('driver', models.CharField(default='Vendor', max_length=500)),
                ('day_production', models.IntegerField(blank=True, null=True)),
                ('total_trip', models.IntegerField(blank=True, default=1, null=True)),
                ('first_trip_ton', models.IntegerField(blank=True, null=True)),
                ('second_trip_ton', models.IntegerField(blank=True, null=True)),
                ('third_trip_ton', models.IntegerField(blank=True, null=True)),
                ('fourth_trip_ton', models.IntegerField(blank=True, null=True)),
                ('fifth_trip_ton', models.IntegerField(blank=True, null=True)),
                ('sixth_trip_ton', models.IntegerField(blank=True, null=True)),
                ('trip_ton', models.IntegerField(blank=True, default=0, null=True)),
                ('routes', models.ManyToManyField(limit_choices_to={'is_active': True}, to='vms_app.route')),
                ('vehicle', models.ForeignKey(limit_choices_to={'is_active': True, 'is_working': False}, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_shift_set', to='vms_app.vehicle')),
            ],
            options={
                'unique_together': {('shift_name', 'vehicle', 'created_date')},
            },
        ),
    ]
