# Generated by Django 5.0.1 on 2024-02-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0031_route_is_working_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='estimation',
            new_name='km_estimation',
        ),
        migrations.AddField(
            model_name='shift',
            name='time_estimation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
