# Generated by Django 5.0.1 on 2024-02-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0032_rename_estimation_shift_km_estimation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='estimation',
        ),
    ]
