# Generated by Django 5.0.1 on 2024-02-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0033_remove_route_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='time_estimation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
