# Generated by Django 5.0.1 on 2024-02-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0037_alter_route_time_estimation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='time_estimation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='time_estimation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
