# Generated by Django 5.0.1 on 2024-02-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0038_alter_route_time_estimation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivity',
            name='routes',
            field=models.ManyToManyField(limit_choices_to={'is_active': True, 'is_working': False}, to='vms_app.route'),
        ),
    ]
