# Generated by Django 5.0.1 on 2024-02-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0039_alter_productivity_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='routes',
            field=models.ManyToManyField(limit_choices_to={'is_active': True, 'is_working': False}, to='vms_app.route'),
        ),
    ]
