# Generated by Django 5.0.1 on 2024-02-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms_app", "0042_alter_triphistory_shift_alter_triphistory_trip_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="km_estimation",
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="shift",
            name="time_estimation",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="triphistory",
            name="is_current",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name="triphistory",
            name="trip_remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shift",
            name="shift_remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shift",
            name="start_image",
            field=models.ImageField(blank=True, null=True, upload_to="shift_start/"),
        ),
        migrations.AlterField(
            model_name="triphistory",
            name="trip_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
