# Generated by Django 5.0.1 on 2024-02-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms_app", "0044_alter_route_time_estimation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="triphistory",
            name="trip_load",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
