# Generated by Django 5.0.1 on 2024-03-02 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms_app", "0045_alter_triphistory_trip_load"),
    ]

    operations = [
        migrations.CreateModel(
            name="fuel_master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[("P", "Petrol"), ("D", "Diesel"), ("G", "Gas")],
                        max_length=1,
                    ),
                ),
                ("fuel_km", models.FloatField()),
                ("fuel_Time", models.DateTimeField()),
                ("fuel_quantiry", models.FloatField(default=1)),
                ("fuel_cost", models.FloatField(default=102.6)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_fuel_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_fuelupdate_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicle_fuel_history",
                        to="vms_app.vehicle",
                    ),
                ),
            ],
        ),
    ]
