# Generated by Django 5.0.1 on 2024-03-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms_app", "0046_fuel_master"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fuel_master",
            name="fuel_Time",
        ),
        migrations.AddField(
            model_name="fuel_master",
            name="fuel_Date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fuel_master",
            name="fuel_km",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
