# Generated by Django 5.0.1 on 2024-03-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0048_rename_fuel_master_fuelmaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productivity',
        ),
    ]
