# Generated by Django 5.0.1 on 2024-03-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0049_delete_productivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelmaster',
            old_name='fuel_quantiry',
            new_name='fuel_quantity',
        ),
    ]
