# Generated by Django 5.0.1 on 2024-03-13 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0051_rename_fuel_date_fuelmaster_fuel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintanence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='fuelmaster',
            name='vehicle',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_fuel_history', to='vms_app.vehicle'),
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('work_start_at', models.DateTimeField(blank=True, null=True)),
                ('work_closed_at', models.DateTimeField(blank=True, null=True)),
                ('work', models.CharField(blank=True, max_length=250, null=True)),
                ('spares', models.CharField(blank=True, max_length=500, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('mechanics', models.CharField(blank=True, max_length=500, null=True)),
                ('driver', models.CharField(blank=True, max_length=500, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_maintanence_history', to='vms_app.vehicle')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshop_jobs', to='vms_app.workshop')),
            ],
        ),
    ]
