# Generated by Django 5.0.1 on 2024-03-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0053_maintenanceschedules_delete_maintanence'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_mechanic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_zonal_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='zonal_manager_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
