# Generated by Django 5.0.1 on 2024-03-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0054_employee_is_mechanic_employee_is_zonal_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Working', 'Working'), ('Completed', 'Completed')], default='Assigned', max_length=50),
        ),
    ]
