# Generated by Django 5.0.1 on 2024-03-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0056_vehicles_rto_details_rename_street_route_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
