# Generated by Django 5.0.1 on 2024-03-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0057_zone_zone_code_alter_route_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='ward_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
