# Generated by Django 5.0.1 on 2024-03-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0058_ward_ward_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triphistory',
            name='total_trip_load',
        ),
        migrations.AlterField(
            model_name='triphistory',
            name='dry_waste',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='triphistory',
            name='green_garbages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='triphistory',
            name='household_hazard',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='triphistory',
            name='inerts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='triphistory',
            name='other_waste',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='triphistory',
            name='recyclable_waste',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='triphistory',
            name='wet_waste',
            field=models.IntegerField(default=0),
        ),
    ]
